#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-08-09 四 09:38
#+TITLE: 不积小流无以成江海的上宜
#+DESCRIPTION: 给小孩起名的三两事
#+TAGS: life,名字,起名,上宜,hipda，qq群,楚辞,离骚
#+CATEGORIES: life

* 前传
前传当指他爹。
当年我起名最简单。
父亲在大队里给我落户时，还没起好大名。和众人起一个，发现已经有叫的了，再起一个，又有人用了。旁边或说，“刚些业了”（gang这个音在那指“都”的意思），于是又有或说那就叫刚吧。
过程是简单，这名字用着在父母心目中就如同看自己的孩子一样，总比别的孩子的好。
现在来看，之所以说名字重要，我个人的观点主要在于它确实在潜移默化中会产生一定影响。
所以这次起名中，像取自评价李白的词“飘逸不群”之“逸群”，就没有选择。太有魏晋风度了，以后即使走艺术之路，若是含有这样性格，恐怕也让为人父母的担心。
顺带说下我小名，更容易，谐音且也不错。出生后那天天还蒙蒙亮，爷爷就跑到父亲家，说小名给起好了，因着梦里有一军队驻扎在家里，就选用这其中两个字吧。这名字就谐音了“祝君”，也顺便接受了无数“幸福”、“快乐”。
* 正传
** 论坛
在出生的当晚，闲来也到论坛中按惯例，发了一个欢乐起名贴，这是以欢乐为主，当然不必太严肃。
收到不少名字，但由于是李姓，欢乐成分未免不足。起的名字宜男，宜中，宜树，李字宜，邦、妈、满、家、龙、权、丰、聃、涵、大、心、安、相、守、正、诚……
同时也收到了更早时候在0110论坛的朋友的祝福，竟然说依稀记得当年头像……
还有说出当年的老梗，由于十分钦佩楼主，不得不说一声好。
** 群
一帮单身的时候相识的朋友，好多已经成为至交，只是我脱单了他们基本都还在奋斗中。感谢祝福同时也希望大家早点。
至于名字，基本就是乐、月、痕、星等等字为主了。
最认真的还是当大哥的，受小窗委托后，起的字还真是都不错，有数个是我曾认真考虑的，譬如乐悦超京相丰亦成学保润 得路等。
** 还有
当妈的考虑的是「玉景」等，当奶奶的考虑的是玉，当爷爷考虑的是升，当姑的是海洋，都是不错的字。
我自己可以说是阅遍古典经史，读尽诗词歌赋。离骚、诗经自不必说，信了男离骚女诗经之说，早至上古十三经，《汉书》、《梁书》二十四史，晚至人间词话，更有维基文库的《汉书人物列表》、《唐书人物列表》等。想了无数字，就是没有太满意的。
最后选择的字，我认为是简洁、有气质、脱俗，字是最简单的，上小学的时候就学的第一个字，笔画也是最少的，只有三笔。意义上自不必说也算积极向上，意境上来说，本来想不使用辈分用字，譬如“涧溪”，和姓连在一起就是一幅优美的图画，但这词的谐音在近期也非上佳，再者我爷爷名字就是溪兰。现在选的这字，意境上和姓连在一起，倒也说得过去。另外至少脱离了琼瑶阿姨那一类港台范的味道。其他方面，还是开口音，叫起来也算响亮。更重要的，对于老家来说，总算是没有重名的。
坦白说这有点过于纠结了。现在再认真的起名，也只不过是一个中文的代号，再说，或许英文名字更重要呢？
* 别传
最后我和个别朋友说名字起好了，叫李戬「明玉」，能认识的不多，我只好依次解释，“戬”就是晋戈＝禁止谷歌，揭露中共闭关锁国的嘴脸，小名叫谷歌，叫大家都知道世界上还有这样一个网站。
这种生辟字起名法，基本上，除了受骂，受到众多反对是无疑的了哈哈。
