#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2017-05-23 二 22:02
#+TITLE: 十一年zz
#+DESCRIPTION: 这是一篇转载，写得不错。
#+TAGS: life, 情感, 转载, zz
#+CATEGORIES: zza

author: qglaci
其实按照国际惯例我应该在开头写上时光荏苒白驹过隙之类的废话。虽然我很不屑而且不在乎，可是事实上时间确实就像是和我们玩丢手绢的小伙伴，她嬉皮笑脸的用手遮住你的双眼然后转身就跑，当你想起来我该去追她了的时候，睁开双眼，才发现周围早已不同，你想抓住她也早已成为了一种奢望。没错，就是这样。

11年前我还是个只有150斤的瘦子，还能打三个小时的篮球，还是个一脸懵逼却自以为与众不同的高三的少年。如果能够称为少年的话，对了，至少是个处男。我在那个大家一心想着高考之后应该怎么玩的时间注意到了我的妻子，我用了最拙劣的泡妞方式，每天不停的传给她纸条，放学不停的发短信，死皮赖脸的叫老婆得到了她。在一起的方式很大众是吧，没什么不同，普通到加上几千组华丽的辞藻推给郭小四那个抄袭狂都没法写成一部让人45度角仰望天空可以泪流满面的小说。一直到高中毕业之后我从死亡的身边把她拉回医院。我突然有点庆幸，这么说可能有点残忍，可事实就是这样。我其实就是个没有什么耐性的人，手机会经常性的还，车子也是开一两年就会腻，我有时候都觉得自己如果没有遇到我的老婆我应该是个花心的人，一切都转变在那次毕业之后我站在马路上接她的电话把她从死亡的手里抢回来。我站在急救外面看着洗胃的她，我知道我离不开她。这就是我的女人。

喏，我就是那个倔强的和时间玩丢手绢的孩子，11年就这么过去了，过得我觉得似乎就是11个月。我就这么从一个150斤的标准体重变成了一个190多斤的大汉堡。变成了一个只能打三分钟篮球，是个抛弃了理想和方向对着现实卑躬屈膝的胖子。我只想好好的活着，让她们活的更好，理想和尊严多少钱一斤我都没有买过，也不想知道价钱。我是个理性到可以欺骗自己是非常感性的人，这句话很拗口，读懂了就不会尴尬。

11年，我知道我的老婆还留着11年前高中时候我写给她的各种纸条，她有序号的编辑好，藏在一个自以为我不知道的地方，有一次我找东西无意中发现的时候觉得，没错，那个跟我玩丢手绢的时间，我他妈抓住你了。

因为我们忘记了我们到底是哪天相爱，所以索性就把每年的5月20作为恋爱的纪念。今年是第11年，我今天早上睡醒的时候一转身，看见她四仰八叉的躺在一边，而另一个小小的她肆无忌惮的趴在我们中间抓着我的被子，忽然觉得很温暖，虽然我不会再找到那个把手绢丢在我背后的时间，但是我终于不再恐惧。

我没有了，也不会再有了青春。却得到了你，现在是你们。

感谢11年的陪伴，感谢在我每次试图在生命中挣扎时，在我身边孤注一掷的你。

最后的最后就是其实我真的是个精神死亡恐惧者，但是在我写下这些的时候，脑海里回荡的都是那个国内伪英伦乐队果味VC的歌词。

直到世界尽头也不是终点，只要我们的爱没有入眠，就在世界尽头的烟花下面，你会相信，我说的所有。
爱有一天会拯救我，所有的恐惧。

是的没错，不过我一直在信，拯救我的不会是爱，是你。

谨以此文给在我身边11年的妻子。
