#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-08-06 六 14:34
#+TITLE: 大法dpt-s1使用小记
#+DESCRIPTION: 
#+TAGS: 大法, dpt-s1, eink, 电纸书, sony
#+CATEGORIES: mobile

* 购买
4月份托美国朋友人肉带回，当时价格是799$。购买动力是作显示屏，计划先花700￥由本坛技术大牛root，再花300￥使用本坛另一技术大牛的显示器同步软件。
到手后，由于看到的放毒贴太多，对重量和大屏并没有什么很大的感觉，对没有前光和分辨率也没有特别的不适，虽然手头有细腻分辨率＋前光的kobo hd。
到手仔细咨询后，对将其当作显示器的效果基本降到冰点，于是破解和软件购买的费用就不再能承受。
于是转为专心看书的工具。
* 看书
这些年购买过的电纸书有kindle dxi, kindle 3, nook2&3, kobo hd，无一例外都是用来折腾。现在这本不舍得破解的s1捏在手里，没法折腾了，只好专心看书了。
此时才发现，这家伙看书真的是太毒了！
** 轻
重量，首当其冲最值一提的是重量！
说捏着一张纸在看书是夸张，说拿一张较厚一点的硬纸板在看书，那就是恰如其分了。举实例来说吧。
有个周末问媳妇s1、kindle3、iphone 6s plus哪一个重哪一个轻，她掂了后说当然是6s，k3也比s1重。其实我也有这错觉，当然我是查过它们的重量6sp仅200g，k3 200多g，s1460k。但它给人的感觉就是这样轻！这恰恰又是它另一个优点——屏幕就是大——带来的。当时家里的另一位客人也是这样的错觉。
它轻到用大拇指和食指捏住一个角看书，毫无压力！这种飘飘欲飞的感觉，也是错常见的来源。而6sp（我刚才专门去捏了一下），感觉要重一点。这样比虽然违反常理，但事实和感觉就是这样。当然，最重要的是我自己就常常这样捏着看书，每次都感受和感叹主于这份重量。
能将这样大的屏幕作成这样轻的感觉，基本上就不必考虑比它小的电纸书了。
** 簿 
如此的轻及轻于其它电子产品的错觉，除了屏幕大的原因之外，就是簿造成的了。
我一直怀疑它电路板在底端一条、电池簿簿软软的两三层聚合物电池贴于屏幕背后，然后加一个后壳而已。
真的很簿。相对于大来说。这也是基于柔性屏才能做到的又大又簿的产品。
* 背壳
** 优点
开始拿到产品时，看错了背壳的材质。
整块背壳竟然采用的是拿破仑皇帝时代刚刚提炼出来、昂贵得超过黄金的Al-235材质！
包括笔夹、micro-USB充电口在内的整个后壳，都是一体铸造成型的。
流着通红高温的铝汁直接倾倒于带着大法工艺要求的精细模具中，几乎未作打磨就直接进入下一道喷漆工序中了。
敦实的USB口和笔夹开口，绝非常见的那种在轻簿的或金属或塑料中开口的设计，而是像拿出一段铁轨、用凿子在上面凿出一个厚实的插孔。
由于材质的原因，硬体的手感上升到另一个层面。
** 缺点
大法的设计好，出自他考虑全面。e-ink产品的外壳用白色，是我一直不能忍受的，会把屏幕对比的特别灰暗。
大法于是把壳弄成黑的。
前壳的四周盖板用的黑色的塑料条，当然，也挺厚实。
看不过刚才说了材质了，但大法要和前壳统一，也要弄成黑的。其实灾没必要呀，又不拿后壳来对比屏幕。再说，实在要黑色的，可心借鉴灰色版本的ipone壳嘛。
大法只是拿个油漆给涂两层。上色防锈是簿簿一层、外面再来一层厚厚的、打浆也似的大黑漆。
结局就是夏天里我每次看书指甲都能扣下一块块的漆皮。
然后我只好索性把四个边的漆全部刮掉。
世界清静了。
所幸完美。铸铝闪着工业精神的光辉。手感也极佳。
* 其他
** 分辨率
还得专门细说两句。
我并不觉得分辨率很重要。我平时用k3和kobo，感觉也差不到哪里去（须知我是对细节非常苛求的有些神经的）。
k3的分辨率低，但渲染伯克利太好了！以前我有篇帖子说过nook2和k3的对比，nook2或3无论经用什么字体，都有些发虚。而k3用华文中宋，简直是细腻清晰得像300ppi屏（主要得益于它对华文中宋的细横无意间「k3本没中文」优化得太精确不发虚）。
而s1字体优化不太到位，和其他（我只用过nook）android系统的机子一样，有些虚，不太让我接受。
但它又没有锯齿化选项（很多时候为了绝对清晰我宁愿用锯齿化字体），更为遗憾。
** 前光
没有。稍有不便。不过也能更好的保护眼睛，光线不好就开灯，不能开灯就不看。
这两点无可否认是产品时代的体现。
** 手写笔等不说了，其他帖子中说得很好了。很好用。舍不得一直磨笔尖。
* 与其他产品的对比
如果没用过s1，或像我初衷一样想挪作它用，可以考虑。
否则，仅仅就是“轻”这一条，我真的太希望你拥有大法sony dpt-s1了。
* 附：书籍和格式
首先是阅读一切书籍没有问题。
这条大优点，使人在下载书籍、收藏书籍时，不必有任何顾虑，只须选择最好、最喜欢的版本。
（我找了一点坚版pda扫描书籍，还有红旗家庭藏书——这就是矢量字体的出版印刷文档啊！）
其次换字体和把所有其他格式打印成pdf，也只是举手之劳，教程和小软件多多，不必再说。

