#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:t timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-05-12 四 23:23
#+TITLE: 孩子“不听话”不是孩子的错zz
#+DESCRIPTION: 
#+TAGS: 家庭,教育,zz
#+CATEGORIES: zza
#+EXTRA-YAML-HEADERS: theme: \nplugin: \nscheme-text: "#ffffff"\nscheme-link: "#ff8540"\nscheme-hover: "#"\nscheme-code: "#"\nscheme-bg: "#6b1606"\nscheme-hero-text: "#8d3700"\nscheme-hero-link: "#ee4000"\nscheme-hero-bg: "#ffb580"\n

#+BEGIN_HTML
<img src=/assets/img/img_2016_05_12__23_26_47.png>

#+END_HTML

常常听到一些家长抱怨：“现在的孩子越来越不听话了！”还有些家长经常跟孩子讲：“要听话啊。”回家后询问孩子一天的情况时也会说：“今天有没有听老师（或者是家里人）的话啊，乖不乖啊？”

每当听到这样的话，我都会问一句：“你所指的不听话是什么？你所指的乖又指什么？”

听到的答案无非就是，出门玩的时候，在某一个地方磨磨蹭蹭不走；天冷让她多穿一件就是不肯穿；又没下雨非要撑着伞出去；刷完牙迟迟不出来却在那里玩水等等，总之让她往东她偏往西。

归根结底一句话，如果孩子没有按照成人的意愿去做，就被称之为不听话，不乖。

每个孩子出生后，都对这个世界充满了好奇，正是因为好奇让她对这个世界有更多的探索。当她开始慢慢长大，她有了自己的思想，想按照自己的想法去做。比如三岁大的小孩已经开始自己选择每天要穿的衣服，也许一开始她的搭配很怪异，一般家长们都会否定小孩的想法，要求按自己的审美观来穿衣，有些小孩坚持自己，就会被训斥为不听话；有些小孩屈服了，慢慢也就没有了自己的主见。

从小，我的衣服都是姐姐搭配的，刚开始我都会讲自己喜欢这件不喜欢那件，被她多次否定以后，我基本就屈服了，渐渐没了自己的想法。直到长大以后很久，我对于自己如何穿衣都是没有主见的。

所以，不要以不听话的名义，去扼杀孩子自己的想法，不管她开始的想法多差，多么不合时宜，她总会从中慢慢寻找到适合自己的风格。穿衣是这样，人生的其他选择都是一样。

有人会说，那孩子想干什么就干什么，错的也就不管了吗？

当然不是。如果要指出孩子的错误，请具体的指出，并解释原因及这样做的后果。比如小孩自己说要留长头发，但是经常晚上洗了之后，想去睡觉，又不愿意用风筒吹干。我说那就剪短一点，很快就吹干，这时奶奶便来威胁：“对啊，你不听话，明天就给你剪了去！”这样小孩就很困惑，又被莫名的盖上了不听话的帽子。如果这样来沟通：“你觉得吹头发麻烦，要么就白天洗，这样时间可能不够，或者剪短一点很快吹干就可以睡觉。如果不吹干，头发湿了睡觉会头痛。”这样做一是有效的进行了沟通，二是孩子也会权衡，会为自己的选择负责。

不要以为小孩小，就可以以威胁的方式，也不要打着我为你好的名义，一切为小孩做主，让她变成所谓的听话的孩子。这样做，只是一时省了事，以权威压制小孩的意愿，但是等她长大，你又会怪她没有主见，没有责任心。

我们为什么要把孩子教育成一个听话的，处处按照大人的意愿去做的人呢？试想一下，你中午吃多了，晚上喝了一碗汤就饱了，但家人不停的跟你说：“你快吃啊，喝一碗汤怎么够？要吃饭和菜，不吃怎么长身体？快点吃了，吃完了才能离开饭桌？你怎么这么不听话......”这时，你是不是很烦很郁闷？对于小孩吃饭，这样的话有几个父母没有讲过呢？小孩子很难去反驳，心里不知有多郁闷。

把每一个小孩当做一个有自己想法的个体去对待，平等的去对话，培养一个有思想的快乐的孩子，而不仅仅是听话的孩子。


文／艾羽勤（简书作者）
[[http://www.jianshu.com/p/907c3c09eeaa][原文链接]]
著作权归作者所有，转载请联系作者获得授权，并标注“简书作者”。
