#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-11-15 二 22:45
#+TITLE: 对于我喜欢的一个论坛的忧伤
#+DESCRIPTION: 
#+TAGS: hi-pda, it, 0110, 论坛, 发展
#+CATEGORIES: soft

/如果有从0110论坛(前身东北网，后方只称0110)来的网友，也许会看过我在零几年刚出iphone且未出google第一代htc那款手机的时候写的帖子，呼吁0110论坛转向。/
/结局就是0110论坛失去支撑手机及品牌从见颓势到成为『无可奈何的花落』。现在想找那篇帖子都找不到。/
/今天脑袋中也是突然冒出一个对hipda论坛的担忧。/
/解决方法我想还是找一个支撑。/
* 曾经的论坛与百花齐放的时代
我来hipda并不早，2010。之前一直在0110。
那个时代pda如日中天，相关论坛也不少。靠那个特殊的时代，pda也算是世界范围内的"大众"产品。这也是相关论坛的立足之本和发展基础。
在基础广泛的前提下，咱论坛从pda切入。pda整个发展史我差不多正好错过，但我想和0110没有本质区别。0110也是靠着一款定制性可玩性无以复加的6688手机发展壮大。
pda和6688如果深入玩进去，需要技术提供。咱这两个论坛就是首先能凝聚起技术大牛，在0110论坛是『cool狼』和一个漂亮美眉『云起·云落』两位，技术登峰造极。
除了技术大牛，反推就是论坛成员的构成。在普通的手机和电脑中再选择使用pda或6688，本身就是一种过滤，这部分人有些小小的不满足、有些小小的完美要求，还稍微有点动手能力。(可能还有闲得蛋疼的充裕时间)好了，人员构成就是人以群分物以类聚的这些人。
这是一个兴盛的时代。
* 从兴盛到衰落
衰落来得如此之快。每一个手机，都已经有了pda的全部功能，palm为代表的pda反身努力追赶手机，但是悲凉的失败了。算作pda的另一支，黑莓也残喘到了头。
pda是这么种东西：一个电子屏幕、一支电子笔，代替纸来办点公。
黑莓是这么种东西：有一个全面小键盘，安全快捷的处理些电子邮件。
二者共同的特点，和撮合到一起的这一小堆人完全一致：有点德味的。
* 淹没到洪流中
你发现没有，有一群人，陷入到存在的疑惑之中。
(前面我有篇帖子略有涉及)画家、书法家、作家、哲学家、音乐家等艺术家。
昨天嘉德拍卖会9000万成交的张大千《巨然晴峰图》，号称含税1.35亿、6年涨40%。这算法也是了特了，两头税都算到涨幅了。实际涨幅只有7.5%。年均利率都没跑过，更不必说通货膨胀了。
有画家的时代，没有照相，没有摄像，往前追溯没有文字。有书法家的时代，没有电脑用来打字。《快雪时晴贴》和《鸭头丸贴》本身只是日常书信。最早有作家的时候，人们只能读书。再说《圣经》和《史记》也只是记录历史。哲学起源于对世界形成的认识，赫拉克利特说世界起源于火，从这发荏到现在，世界只存在于科学家的实验中了。
这一部分人，曾经远远的站在其他所有人类之上，生存于纯精神领域的稀薄空气中，不管他人头攒动思想还是作品，无不闪耀着完美主义的光辉。
但现在，他们找不到于栖身之处了。看不到尽头的庸俗之众随着时代走到最前面，占据了他们的栖息之地。
就像咱们的论坛。
虽然说遗老遗少算不上天才或艺术家，但至少本来有那么点不同于众。
虽然说没冒出那么多人，最大的板块甚至不对外爬虫，但也有不少人渐渐加入进来。
* 外界有关电子产品的世界
只说和咱们关系近一点的。我不太认同apple创造的这个全触摸的、把全键盘斩尽杀绝的世界。
我现在还用着全键的kindle 3，因为我找不到一个能更方便控制的触摸屏的产品。正如不管你用哪一款iphone or android,你也会在午后追忆起palm的键盘和系统or黑莓的快捷拔号和输入。
就和艺术家们被淹没了一样，iphone and android淹没了所有可能的产品。外表稍有差别的产品都不太可能，更不用说像siemens一年内推出数款奇形怪状手机的时代了。
究其原因，我认为是一个产品面对越多受众的时候，它就必须越简单、越傻瓜，就像木桶理论，用最短的那根木头来定水位。(所以锤子怎么可能成功，情怀总被嘲笑。其实只是庸俗者以为和他站在同一水平高度的庸众们的支持就是判断标准而已)
所以大家会和我一样，在未来也不可能再逆流而上得到一款可以高度定制、超级复杂的通讯产品了。
* 从产品到人
电子产品事小，人，事大。没有产品的依附，在这个论坛里，也就不可能再增加同水平同旨趣的同好。
从pda开始，我们论坛凝聚起这样一群人，是历史的偶然，但这群人有强烈的共同本质，这一点就决定了论坛能维持到现在有它的历史必然。
静水流深，但也死水易腐。深度够，但是没有新的产品维系，没有新人、新的技术型血液充实，那就只能日渐衰朽，正如同我们这群人的年岁一样。
论坛从讨论技术，到讨论孩子、到家庭矛盾和离异，完全就是"原始积累"的这群人的生命轨迹。后面，相信就是讨论退休和死亡了。
新人其实也有。
除了数量不多之外，重要的是压根就不是一类人。他们不是基于对一类产品带有点拜物、较真及追求极致这样的性格。
所以在这个论坛里，即使是谈论着日常琐事，但话题、行为、语言、思想和性格，都那么泾渭鲜明。
衰老、侵蚀、离散，虽然很不显眼，但每天都发生着。
譬如现在，这个黄金时段上线高峰的时刻却只有3100人在线。美国组织起来真刀实枪打回古巴的流亡者，还能达到1400人呢。不用冒生命危险的键盘党，才3100人，且估计大部分也已经是老、弱、病、残了。
* 看看论坛的版块吧
全天能超过10个贴的版块就三个，D版、BS版、EINK版。
** eink版
那么说，现在能提供点发展支撑引进新人的版块就只有一个eink版了。
eink能吸引的是什么人？和以前靠技术吃饭的版块完全不同。吸引的是爱读书的、不爱折腾(也有兼而有之的)、来下载点盗版书籍的人们。靠这个，是发展不起人气的。恰如小米系的多看，从刚成立折腾kindle2时我就接触过，到后来投入小米系，到现在，也没有特别大的发展。讲电子书，比amazon差了光年，讲软件，从附庸kindle起家，没没进过榜单，讲硬件，和汉王的影响力比也是差之光年以计，估计也就是比米聊的处境好点。其实也不是发展的不重视或不努力，而是"阅读"这件事本身，已经就像是前面说的那些艺术门类一样，不再是这个世界里的人类能再投入时间和精力的一种稀缺品了。
那么靠eink版还能有什么指望。当然，估计本身也没被指望过。
** BS版
靠着穷屌丝、贪图便宜的人们，续命很难。
随着社会发展，一些物品的价值更低了。以前为了省钱大多数人选择组装电脑，现在这个行业消失了，人们买整机笔记本。
如果单纯的说bs版"玩"的意义，那么现在网络电商7天无理由退货本身就给了特殊需求的这类人玩的空间。其他网购也可以随时退。
从希奇古怪小玩意角度来说，海淘的方便，也冲抵了这一部分。
再者，旧的物品，可入手价值能有多大呢。今天下午我和同事沿车走了一圈，评论说车灯变黄、缝隙变大、刹车盘变薄、车底油渍多，物品都是有使用折旧的，都是整体性的损耗。
那bs的意义可能真的只是剩点特殊要求的求购而已了。
至于商家出了过路费，所得能抵回来吗？再说商家的信誉，和慈善的伤害一样，都有走低的趋势吧。
不过还是很感谢至少到现在，提出过的要求都很快得到帮助。
** D板
这是集聚人气最多、有时候使人有些成瘾的版块了。
但是皮之不存，毛将焉附？D版所有的人，都是来自其他版块。没有技术版的存在，那来的人，不是看热闹的，就是各种无聊人士了。当然还有别有用心者和寻夫团。
非长期醒在它版后来过来的人，哪怕沉淀于此时间再长，也非我族类。
D版的封闭性可能是一个独特的乐园，但封闭性单纯从扩大和发展看还是缺点呢。
这真是个悖论。
* 找什么做支撑
如果是08年，我可以对着0110建议找iphone，如果是10年，我更是满心焦虑的建议论坛把方向转到将横空出世的gphone(当时以为google推出第一部手机可能叫这名字)。
但现在手机界大局已定，windows phone都无法翻盘，谁还能更有能力？即使再有全新系统的玩物，也不是现在能看得到的。
更何况，世界发展到越来越向白痴型、傻瓜型操作的产品一统江湖了，个性、高度定制本身就是除了增加厂商后期维护成本外，无法向普通人推广的东西。
google glass？早死好多年了吧。
VR？如火如荼，涉及系统吗？可改制性有多大。也许是个方向？
当然，世界永远会推陈出新，只要有善于发现的眼睛，有敏感的触觉，也许不难找到切入点。
哪怕是做一个科技博客站点，也许都能达到-世俗意义的-成功。
《京华时报》关门大吉了，更早的清朝遗老遗少，也是他们活到百岁前关张了，他们的子孙，分散到各个地方，甚至都不再是满族，改宗改姓了。
我们和这群人差不多。
