#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-07-01 五 20:57
#+TITLE: 斯宾诺莎站在人类未来和过去的至高处
#+DESCRIPTION: 对斯宾诺莎的简单描述和他理论中普通人无法理解不愿接受的一点看法
#+TAGS: 斯宾诺莎,哲学,罪恶,善
#+CATEGORIES: review

* 
罗素说斯宾诺莎在才智上可能有人超过他，但是在首先方面，他是至高无上的。
这点其实不重要。他自按他自己内心所选择的方式生活。打动我的，是他对善和罪恶的认识与评价。
* 《伦理学》结尾
#+BEGIN_QUOTE
“贤达者，只要他被认为是贤达者，其灵魂绝少扰动。他却按照某种永恒的必然性知自身、知神、知物，决不停止存在，而永远保持灵魂的真正恬然自足。我所指出的达成这种结果的道路，即使看起来万分艰难，然而总是可以发现的道路。既然这条道路很少为人找到，它确实艰难无疑。假若拯救之事近在手边，不费许多劳力可以求得，如何会几乎被所有人等闲忽略？不过一切高贵的事都是既希有同样也是艰难的。”
#+END_QUOTE
* 
善和恶只是来自我们自身狭隘的陋见。它涉及到我们的情感，才具有了评价的标准。使人高兴的就是善、使人痛苦的就不好，但这只是承受的主体发生了转移的原因。
在斯宾诺莎这里，道德的评价是放在宇宙的大视野中论说的。
单个人的灾难，并非宇宙的灾难，对宇宙来说，仅是加强最后和声的暂不谐音而已。
这个说法真是直接响应了中国老子在《道德经》中话，“天地不仁，以万物为刍狗；圣人不仁，以百姓为刍狗。天地之间，其犹橐龠乎？虚而不屈，动而愈出”。
不仅是个人的灾难，而且将人类的苦难放到宇宙中说，上起自时间的开端（如果有的话。这又是一个哲学命题），下止于时间的尽头，那灾难就不是个人的灾难，也不是人类的灾难，更非宇宙的灾难，它只不过是流和逝，也是更迭与新生。
能将眼光看至时光尽头，再返回来理解善与罪恶等词语的定义，相对就容易得多。
灾难也好，悲伤也好，只是自然法则的一个部分，渺沧海之一杰。
#+BEGIN_QUOTE
“憎受到憎回报则增强，但反之能够被爱打消。为爱所彻底战胜的憎，转化成爱；这种爱于是比先前假使没有憎还大”
#+END_QUOTE
这句里又像在叙述普世的道德。虽然斯宾诺莎终生没有被认为是信仰神的，延伸到一个世纪里都被认为是“坏得可怕的人”，但他全部的哲学还是贯彻着“神”的观念。
幸好，在神学与科学逐渐单独的地位后，显现出斯宾诺莎难以企及的真诚和崇高。
* 
《圣经》说你怎么能只看到你兄弟眼中的刺，而看不到自己眼中的梁木呢，又说如果你的兄弟打你左脸，应当把右脸凑过去。这是从宗教意义上的博爱精神。用爱来回馈恨。
在这点上，斯宾诺莎即从时间与宇宙的无限性来反推爱与恨的短暂与微末，这也是他使我感到是站在时空序列的至高点看待这个世界的印象形成原因。一种至博至广的爱，简单的说就根本不在乎恨，甚至不会在乎爱本身。“受一个单独的炽情主宰的生活是与一切各类的智慧皆难相容的狭隘生活”。
但罗素在此处，对斯宾诺莎的诘难举例颇失当。他说如果遇到惨酷被伤害的家人，“也应该保持哲学的平静吗？”
此时也只能遗憾罗素无法理解斯宾诺莎的高度了。
古希腊时代的斯葛多派说，“哪怕我一家人受罪，对我有什么关系？我照旧能够道德高尚”。罗素以现代人的观念，仰望着斯葛多派的话语。
在斯宾诺莎的话里，意思却并非和他们一致，而是让人不自觉的感到，他的视力所及，还是在于宇宙，而远非转瞬即逝的生命或者世人强加于你我的是非善恶。即使那时是科学与天文刚刚开始发展的时期，他的观念，也远在未来的山峰上等待我们。

