#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-07-20 三 13:19
#+TITLE: 生命诞生
#+DESCRIPTION: 
#+TAGS: life, 育儿
#+CATEGORIES: life

* 前情提要
16日凌晨，周六，刚睡没多久就被叫醒。在40周足月又推延几天后，终于小宝宝有了动静。
打了120没有接通的情况下，没有再拔，新说直接开车去吧，于是就收拾东西出发。
除了衣服和必备的用品，我又拿了满满一包电脑及其他电子产品。小衣服拿了十几件，简直像要出远门住几十天的样子。最好笑的是娘，只顾照顾我们，自己的鞋子都忘了换，穿着拖鞋就走。
由于是凌晨路上车少，开得相当快，去到医院是凌晨2点多，例行测胎心等等，折腾了大半夜，最后因产征不明显，又回到家。
这是待产前激动紧张的一个凌晨。
* 产前一天
周六日在家等了两天，还没有动静，周一按约定去医院办住院手续了。
去到之后没有独门病房，护士站的回复说你们应该早点到，8点前是有的，或者是预约。这时我才知道可以预约，对准孩妈一直传递的靠关系这一假信号颇为不满。不过也没办法，只好先住一天三人间。当然条件差是不必说的。
中午测了两次胎心，给医生看说不太好，还是说太平衡，不强烈，建议做顺产测试。
我详细的问了测试内容，回答说使用一半催产素，如果胎心情况好就顺产，如果差就剖宫。听着颇让人担心。
在整个孕期，我对新的身体条件和孕宝宝的情况还是了解的。现在的情况，在我心中只是胎宝宝在安静的睡觉而已。因此，征得医生的同意，下午再让我们测一次看看那会儿的情况如何。
结果当然很好。一是午后有她闺蜜前来倍伴，二来我在旁边大声讲话、念书，刺激胎宝宝的运动。所以这关就安然度过。
晚饭后，我们又一起去了奥森沿湖边走了一圈。一 边走一边兴高采烈的拍短视频。我说这是产前一天的纪念，新说你怎么知道是产前呢。其实只是说说嘛，也许就是那么快了呢。
* 生产的日子
夜里见红。可见宝宝是多么配合。既免去了一次让人担心的测试，又使人把心放下了。
但医生建议今天就使用催产素了。我心里老大不情愿。在我意识里，早天晚天，完全不必根据所谓的预产期计算。但在长期的新的焦虑中，尤其是她关于胎便的错误认识，严重影响了我的判断。没有好好学习胎便的知识，导致我同意了医生的建议。
其实根据后来排胎便的过程来看，很简单的可以知道，不生出来而是在子宫中，是不可能排胎便的。
租击了昨天的医生建议，今天的还是没有能选择我认为更正确的。过早的挂催产针，结果就是人为制造提前的宫缩，让新受了十四个小时的疼痛。
后来的生产过程也证明我在整个孕期中的判断。一切情况都超级好，山清水秀。
* 新生命诞生
在这个星期二，7月19号，农历六月十六晚10点31分，新顺产生下8斤1两男宝宝一个，新的征程开始了。
