#+STARTUP: showall
#+STARTUP: hidestars
#+OPTIONS: H:2 num:t tags:nil toc:nil timestamps:t
#+LAYOUT: post
#+AUTHOR: yefeiyu
#+DATE: 2016-08-16 二 22:11
#+TITLE: 说说过程
#+DESCRIPTION: 干事过程是种享受，有时也是种浪费
#+TAGS: review,观点,过程,kindle 3
#+CATEGORIES: review

我说的过程，在这里主要是指凡事追求一种极致，在极致中享受美的快感。
* 过程是种美
** 泛泛的当下
每个人对生活的追求不同。
有些人追求的是权力和财富，是普遍意义上的成功。
这种想法无可厚非，毕竟目前目力所及的圈子里，人们都是这样界定人生的。
过去可能人们追求的是报国、为苍生谋福利。譬如那句著名的话，为天地立心、为生民立命、为往圣继绝学、为万世开太平。
这些信念，是在儒家教育的体系下养成的。
现在教育没有体系，有的只是愚弄人民。所谓的共产主义信念，早已经被世人从内心认识清楚是永远不可能达到的一种幻想，那么无信念的心灵接受的只能是利在当（党）下的现实利益。
那自然就只能是遍地的权力财富成功了。
如果人生的目的是这样的，那必然要为之抛弃些什么。随手简单的举例，如冷门行业、专业。
** 有种可怜门类的当下
艺术就是这样一种境遇。
粗略的说，涉及艺术的有有三种人。
天才和庸才自然是不二之选。
庸才也就罢了，本来就是毫无才具，只是因为实在没有哵 的出路，学点音体美，从事了这行。
这些倒是和大众比较契和，也差不多是一类人，然后就对权贵和金钱跪舔，使行业表现出一种毫无价值的繁荣假象。
有这类人，既不会是艺术的悲哀，也不会是他们本人的悲哀，他只不过是这样一钟普通的存在，以前有，以后也不会少。
至于天才，这种稀缺资源，是艺术薪火相传的根本。但在这种社会制度下，没再见到哪个领域出现过。
还有一个我个人比较迷惑的方面。
现在是否还有艺术存在的必要？
拿绘画来说，已经出现的摄像摄影，虽然说和绘画没有可比性，但是绘画失去了重要、普遍的现实功用，是否只成为为艺术而艺术的一种行业。
即使摄影，也已经受到摄像的更大冲击。摄像，受到直播的冲击。
世界和技术在进步，一些古老的东西，会逐渐走进历史。
再拿哲学来说。以前是认识世界、发现世界、阐释世界的理论，地位高到所有学科的始祖和发源。
学科一步步发展、细分，直至最微波的领域及最前沿的领域，AI、DNA、clone、机械细胞元等等，即使涉及到伦理学理论，那也在技术进步的眩目光环中，被迅速接受。从基督教推动对巨人社会的领导那天起，就已经不再具备质疑和贵的能力了。信仰也在被势特别是技术的强势所抛弃。
技术本身，已经成为哲学。
无论哪个传统领域，纵或有天才存在及推动该领域的发展，也无法抵挡领域本身的衰亡。
一步步看来，天才已经都如此悲催了，第三种人就只能让人悲哀了。
这类就是附庸风雅、消费艺术品的普通人。
每当遇到此种人，都让人感觉是生活在垃圾场当中。可惜，这种人是如此之多。
** 在可怜当下中的残存感觉
可怜当下中这种艺术门类的消亡，对天才人物来说想必非常痛苦。因为对于非天才的我来说，都已经是比较难过了。
但不管怎么说，如果把过去看成是享受艺术的黄金时代、把未来看成是技术的时代，那和夹在中间的这一年代，就是在毁灭和消亡中品味艺术的美、创造过程的美的残渣这种感觉了。
即使这样，不管在哪个细小东西上，能以一种完美主义的偏执精神，去做什么，也是一种享受了。
* 过程是种浪费
好多时候，这种完美追求的过程，只是一种浪费。
这也是无可奈何的。
即使是能产生出时代经典的、哪怕跨几个时代，到了未来某一时代的当下，也会成为不合时宜的古董。
如果你愿意把其一定要看成是推动什么进步的过程，那我只能说你高估或者说你是在创造一种本来不存在至少有争议几千年也没有解决或回答出来的“意义”这东西了。
世界上每一件事每一个东西，后面要发展或成为什么，都有N种可能，后面只发生了1种而已。
这就像是说一定要把浩瀚至几万亿光年远、几万亿个银河系最后都要2000亿年后被吞噬于黑洞，而这其中像尘埃一样微小而短暂的地球，上面有个上帝掌握着意义与未来一样荒谬。
这就像我花了一年，把kobo hd 上的debian系统弄得让我感觉特别完美，终于可以写一篇东西了，但是却发现kindle 3使用x11vnc却方便了一点那样让人失魂落魄。这过程中本来的兴奋和成就感结果在kindle 3屏幕上显得如此荒谬。
明天，作为kobo hd和kindle 3基础的e-ink技术，被0延时的彩色电子纸代替，设备、系统、……都成为了不堪回首的过去。
在追求完美的幻觉自欺下，浪费的过程如此的荒谬。
幸好它并不比荒谬的人生多荒谬了哪怕0.01毫米。
